services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_NAME=vacation_app

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: vacation_app
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
